# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Operation(object):
    def setupUi(self, Operation):
        Operation.setObjectName("Operation")
        Operation.resize(1217, 819)
        Operation.setStyleSheet("border-radius: 5px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Operation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Operation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet(".QWidget {\n"
" background-color: rgb(218, 218, 218);\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.horizontalLayout_2.addWidget(self.title)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_17 = QtWidgets.QWidget(self.widget)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.language_selection = QtWidgets.QComboBox(self.widget_17)
        self.language_selection.setMinimumSize(QtCore.QSize(0, 25))
        self.language_selection.setStyleSheet("background-color: rgb(236, 240, 241);\n"
"border-radius: 2px;\n"
"")
        self.language_selection.setObjectName("language_selection")
        self.language_selection.addItem("")
        self.language_selection.addItem("")
        self.horizontalLayout_12.addWidget(self.language_selection)
        self.horizontalLayout.addWidget(self.widget_17)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Operation)
        self.widget_2.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.functionalWidget = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functionalWidget.sizePolicy().hasHeightForWidth())
        self.functionalWidget.setSizePolicy(sizePolicy)
        self.functionalWidget.setMinimumSize(QtCore.QSize(450, 0))
        self.functionalWidget.setObjectName("functionalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.functionalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_9 = QtWidgets.QWidget(self.functionalWidget)
        self.widget_9.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_13 = QtWidgets.QWidget(self.widget_9)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget_13)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.verticalLayout_7.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_9)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.quick_start_button = QtWidgets.QPushButton(self.widget_14)
        self.quick_start_button.setMinimumSize(QtCore.QSize(0, 30))
        self.quick_start_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.quick_start_button.setObjectName("quick_start_button")
        self.horizontalLayout_9.addWidget(self.quick_start_button)
        self.horizontalLayout_9.setStretch(0, 11)
        self.verticalLayout_7.addWidget(self.widget_14)
        self.verticalLayout_7.setStretch(0, 3)
        self.verticalLayout_2.addWidget(self.widget_9)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.widget_8 = QtWidgets.QWidget(self.functionalWidget)
        self.widget_8.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_6 = QtWidgets.QWidget(self.widget_8)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.verticalLayout_10.addWidget(self.widget_6)
        self.widget_16 = QtWidgets.QWidget(self.widget_8)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radar_control_button = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radar_control_button.sizePolicy().hasHeightForWidth())
        self.radar_control_button.setSizePolicy(sizePolicy)
        self.radar_control_button.setMinimumSize(QtCore.QSize(0, 30))
        self.radar_control_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.radar_control_button.setObjectName("radar_control_button")
        self.horizontalLayout_11.addWidget(self.radar_control_button)
        self.verticalLayout_10.addWidget(self.widget_16)
        self.verticalLayout_10.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_5 = QtWidgets.QWidget(self.functionalWidget)
        self.widget_5.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.verticalLayout_12.addWidget(self.widget_7)
        self.widget_10 = QtWidgets.QWidget(self.widget_5)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.navigation_control_button = QtWidgets.QPushButton(self.widget_10)
        self.navigation_control_button.setMinimumSize(QtCore.QSize(0, 30))
        self.navigation_control_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.navigation_control_button.setObjectName("navigation_control_button")
        self.horizontalLayout_6.addWidget(self.navigation_control_button)
        self.verticalLayout_12.addWidget(self.widget_10)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.widget_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.widget_15 = QtWidgets.QWidget(self.functionalWidget)
        self.widget_15.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_12 = QtWidgets.QWidget(self.widget_15)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.verticalLayout_3.addWidget(self.widget_12)
        self.widget_11 = QtWidgets.QWidget(self.widget_15)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.navigation_button = QtWidgets.QPushButton(self.widget_11)
        self.navigation_button.setMinimumSize(QtCore.QSize(0, 30))
        self.navigation_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.navigation_button.setObjectName("navigation_button")
        self.horizontalLayout_15.addWidget(self.navigation_button)
        self.sorting_button = QtWidgets.QPushButton(self.widget_11)
        self.sorting_button.setMinimumSize(QtCore.QSize(0, 30))
        self.sorting_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.sorting_button.setObjectName("sorting_button")
        self.horizontalLayout_15.addWidget(self.sorting_button)
        self.charging_button = QtWidgets.QPushButton(self.widget_11)
        self.charging_button.setMinimumSize(QtCore.QSize(0, 30))
        self.charging_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.charging_button.setObjectName("charging_button")
        self.horizontalLayout_15.addWidget(self.charging_button)
        self.verticalLayout_3.addWidget(self.widget_11)
        self.verticalLayout_2.addWidget(self.widget_15)
        self.widget_20 = QtWidgets.QWidget(self.functionalWidget)
        self.widget_20.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_19 = QtWidgets.QWidget(self.widget_20)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.verticalLayout_4.addWidget(self.widget_19)
        self.widget_21 = QtWidgets.QWidget(self.widget_20)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.OCR_identification_button = QtWidgets.QPushButton(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OCR_identification_button.sizePolicy().hasHeightForWidth())
        self.OCR_identification_button.setSizePolicy(sizePolicy)
        self.OCR_identification_button.setMinimumSize(QtCore.QSize(0, 30))
        self.OCR_identification_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.OCR_identification_button.setObjectName("OCR_identification_button")
        self.horizontalLayout_16.addWidget(self.OCR_identification_button)
        self.ARUCO_identification_button = QtWidgets.QPushButton(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ARUCO_identification_button.sizePolicy().hasHeightForWidth())
        self.ARUCO_identification_button.setSizePolicy(sizePolicy)
        self.ARUCO_identification_button.setMinimumSize(QtCore.QSize(0, 30))
        self.ARUCO_identification_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.ARUCO_identification_button.setObjectName("ARUCO_identification_button")
        self.horizontalLayout_16.addWidget(self.ARUCO_identification_button)
        self.QR_identification_button = QtWidgets.QPushButton(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QR_identification_button.sizePolicy().hasHeightForWidth())
        self.QR_identification_button.setSizePolicy(sizePolicy)
        self.QR_identification_button.setMinimumSize(QtCore.QSize(0, 30))
        self.QR_identification_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 128, 185);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.QR_identification_button.setObjectName("QR_identification_button")
        self.horizontalLayout_16.addWidget(self.QR_identification_button)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(2, 1)
        self.verticalLayout_4.addWidget(self.widget_21)
        self.verticalLayout_2.addWidget(self.widget_20)
        self.widget_22 = QtWidgets.QWidget(self.functionalWidget)
        self.widget_22.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_26 = QtWidgets.QWidget(self.widget_22)
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.widget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_16.addWidget(self.label_12)
        self.verticalLayout_5.addWidget(self.widget_26)
        self.widget_23 = QtWidgets.QWidget(self.widget_22)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.joystick_control_button = QtWidgets.QPushButton(self.widget_23)
        self.joystick_control_button.setMinimumSize(QtCore.QSize(0, 30))
        self.joystick_control_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.joystick_control_button.setObjectName("joystick_control_button")
        self.horizontalLayout_17.addWidget(self.joystick_control_button)
        self.keyboard_control_button = QtWidgets.QPushButton(self.widget_23)
        self.keyboard_control_button.setMinimumSize(QtCore.QSize(0, 30))
        self.keyboard_control_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.keyboard_control_button.setObjectName("keyboard_control_button")
        self.horizontalLayout_17.addWidget(self.keyboard_control_button)
        self.verticalLayout_5.addWidget(self.widget_23)
        self.verticalLayout_2.addWidget(self.widget_22)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(7, 1)
        self.horizontalLayout_5.addWidget(self.functionalWidget)
        self.widget_25 = QtWidgets.QWidget(self.widget_2)
        self.widget_25.setStyleSheet("")
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_8.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_8.setSpacing(9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_24 = QtWidgets.QWidget(self.widget_25)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_18 = QtWidgets.QWidget(self.widget_24)
        self.widget_18.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_13.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(11)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.arm_camera_view = QtWidgets.QLabel(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arm_camera_view.sizePolicy().hasHeightForWidth())
        self.arm_camera_view.setSizePolicy(sizePolicy)
        self.arm_camera_view.setStyleSheet("QLabel{\n"
"    background-color: rgb(218, 218, 218);\n"
"} \n"
"")
        self.arm_camera_view.setAlignment(QtCore.Qt.AlignCenter)
        self.arm_camera_view.setObjectName("arm_camera_view")
        self.horizontalLayout_14.addWidget(self.arm_camera_view)
        self.agv_camera_view = QtWidgets.QLabel(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agv_camera_view.sizePolicy().hasHeightForWidth())
        self.agv_camera_view.setSizePolicy(sizePolicy)
        self.agv_camera_view.setStyleSheet("QLabel{\n"
"    background-color: rgb(218, 218, 218);\n"
"} \n"
"")
        self.agv_camera_view.setAlignment(QtCore.Qt.AlignCenter)
        self.agv_camera_view.setObjectName("agv_camera_view")
        self.horizontalLayout_14.addWidget(self.agv_camera_view)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.verticalLayout_9.addWidget(self.widget_18)
        self.verticalLayout_8.addWidget(self.widget_24)
        self.widget_4 = QtWidgets.QWidget(self.widget_25)
        self.widget_4.setStyleSheet("background-color: rgb(236, 240, 241);")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.logger_browser = QtWidgets.QTextBrowser(self.widget_4)
        self.logger_browser.setStyleSheet("background-color:rgb(43, 43, 43);")
        self.logger_browser.setObjectName("logger_browser")
        self.verticalLayout_6.addWidget(self.logger_browser)
        self.log_clear_button = QtWidgets.QPushButton(self.widget_4)
        self.log_clear_button.setMinimumSize(QtCore.QSize(0, 30))
        self.log_clear_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(39, 174, 96);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color:gray;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"    border: 1px groove gray;\n"
"    border-style: outset;\n"
"    font: 75 9pt \"Arial\";\n"
"}\n"
"")
        self.log_clear_button.setObjectName("log_clear_button")
        self.verticalLayout_6.addWidget(self.log_clear_button)
        self.verticalLayout_8.addWidget(self.widget_4)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout_5.addWidget(self.widget_25)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)

        self.retranslateUi(Operation)
        QtCore.QMetaObject.connectSlotsByName(Operation)

    def retranslateUi(self, Operation):
        _translate = QtCore.QCoreApplication.translate
        Operation.setWindowTitle(_translate("Operation", "Intelligent Logistics System"))
        self.title.setText(_translate("Operation", "Intelligent Logistics System"))
        self.label_2.setText(_translate("Operation", "Language Selection"))
        self.language_selection.setItemText(0, _translate("Operation", "English"))
        self.language_selection.setItemText(1, _translate("Operation", "Chinese"))
        self.label_9.setText(_translate("Operation", "Intelligent Logistics Task"))
        self.quick_start_button.setText(_translate("Operation", "Quick Start"))
        self.label_6.setText(_translate("Operation", "Lidar"))
        self.radar_control_button.setText(_translate("Operation", "Open"))
        self.label_8.setText(_translate("Operation", "Navigation"))
        self.navigation_control_button.setText(_translate("Operation", "Open"))
        self.label_10.setText(_translate("Operation", "Intelligent Logistics Tasks"))
        self.navigation_button.setText(_translate("Operation", "Move to Shelf"))
        self.sorting_button.setText(_translate("Operation", "Circular Sorting"))
        self.charging_button.setText(_translate("Operation", "Automatic Charge"))
        self.label_11.setText(_translate("Operation", "Visual Functional"))
        self.OCR_identification_button.setText(_translate("Operation", "OCR Text Detect"))
        self.ARUCO_identification_button.setText(_translate("Operation", "ARUCO Code Detect"))
        self.QR_identification_button.setText(_translate("Operation", "QR Code Detect"))
        self.label_12.setText(_translate("Operation", "Motion Control"))
        self.joystick_control_button.setText(_translate("Operation", "Open Joystick Control"))
        self.keyboard_control_button.setText(_translate("Operation", "Open Keyboard Control"))
        self.arm_camera_view.setText(_translate("Operation", "MechArm 270 Camera View"))
        self.agv_camera_view.setText(_translate("Operation", "AGV 2D Camera View"))
        self.log_clear_button.setText(_translate("Operation", "Log Clear"))
